[2023-12-02 16:54:03,244] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [queued]>
[2023-12-02 16:54:03,369] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [queued]>
[2023-12-02 16:54:03,371] {{taskinstance.py:880}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 16:54:03,373] {{taskinstance.py:881}} INFO - Starting attempt 16 of 16
[2023-12-02 16:54:03,374] {{taskinstance.py:882}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 16:54:03,408] {{taskinstance.py:901}} INFO - Executing <Task(PythonOperator): load_data_psql> on 2023-12-02T15:52:55.287974+00:00
[2023-12-02 16:54:03,416] {{standard_task_runner.py:54}} INFO - Started process 2529 to run task
[2023-12-02 16:54:03,532] {{standard_task_runner.py:77}} INFO - Running: ['airflow', 'run', 'hw-3.4', 'load_data_psql', '2023-12-02T15:52:55.287974+00:00', '--job_id', '25', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/hw-3.4.py', '--cfg_path', '/tmp/tmpzlisrq08']
[2023-12-02 16:54:03,534] {{standard_task_runner.py:78}} INFO - Job 25: Subtask load_data_psql
[2023-12-02 16:54:03,592] {{logging_mixin.py:120}} INFO - Running <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [running]> on host 2cf373442eb7
[2023-12-02 16:54:03,628] {{base_hook.py:89}} INFO - Using connection to: id: conn1. Host: host.docker.internal, Port: 5434, Schema: quotes, Login: postgres, Password: XXXXXXXX, extra: None
[2023-12-02 16:54:04,397] {{logging_mixin.py:120}} INFO - ------------ response --------------
[2023-12-02 16:54:04,399] {{logging_mixin.py:120}} INFO - http://api.exchangerate.host/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&access_key=PO8LZ4A0I0PPI60J
[2023-12-02 16:54:04,401] {{logging_mixin.py:120}} INFO - None
[2023-12-02 16:54:04,402] {{logging_mixin.py:120}} INFO - {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
[2023-12-02 16:54:04,404] {{logging_mixin.py:120}} INFO - ------------ end --------------
[2023-12-02 16:54:04,406] {{logging_mixin.py:120}} INFO - ------------ data --------------
[2023-12-02 16:54:04,407] {{logging_mixin.py:120}} INFO - {'success': False, 'error': {'code': 101, 'type': 'invalid_access_key', 'info': 'You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]'}}
[2023-12-02 16:54:04,409] {{logging_mixin.py:120}} INFO - ------------ end --------------
[2023-12-02 16:54:04,411] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2023-12-02 16:54:04,422] {{taskinstance.py:1070}} INFO - Marking task as SUCCESS.dag_id=hw-3.4, task_id=load_data_psql, execution_date=20231202T155255, start_date=20231202T165403, end_date=20231202T165404
[2023-12-02 16:54:08,208] {{local_task_job.py:102}} INFO - Task exited with return code 0
