[2023-12-02 16:32:17,679] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [queued]>
[2023-12-02 16:32:17,790] {{taskinstance.py:670}} INFO - Dependencies all met for <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [queued]>
[2023-12-02 16:32:17,792] {{taskinstance.py:880}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 16:32:17,794] {{taskinstance.py:881}} INFO - Starting attempt 9 of 9
[2023-12-02 16:32:17,796] {{taskinstance.py:882}} INFO - 
--------------------------------------------------------------------------------
[2023-12-02 16:32:17,821] {{taskinstance.py:901}} INFO - Executing <Task(PythonOperator): load_data_psql> on 2023-12-02T15:52:55.287974+00:00
[2023-12-02 16:32:17,829] {{standard_task_runner.py:54}} INFO - Started process 1688 to run task
[2023-12-02 16:32:17,948] {{standard_task_runner.py:77}} INFO - Running: ['airflow', 'run', 'hw-3.4', 'load_data_psql', '2023-12-02T15:52:55.287974+00:00', '--job_id', '18', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/hw-3.4.py', '--cfg_path', '/tmp/tmp0rbr7b0r']
[2023-12-02 16:32:17,950] {{standard_task_runner.py:78}} INFO - Job 18: Subtask load_data_psql
[2023-12-02 16:32:18,138] {{logging_mixin.py:120}} INFO - Running <TaskInstance: hw-3.4.load_data_psql 2023-12-02T15:52:55.287974+00:00 [running]> on host 2cf373442eb7
[2023-12-02 16:32:18,194] {{base_hook.py:89}} INFO - Using connection to: id: conn1. Host: host.docker.internal, Port: 5434, Schema: quotes, Login: postgres, Password: XXXXXXXX, extra: None
[2023-12-02 16:32:19,091] {{logging_mixin.py:120}} INFO - ------------ response --------------
[2023-12-02 16:32:19,102] {{logging_mixin.py:120}} INFO - https://www.alphavantage.co/query?function=SYMBOL_SEARCH&apikey=PO8LZ4A0I0PPI60J&keywords=ibm
[2023-12-02 16:32:19,104] {{logging_mixin.py:120}} INFO - None
[2023-12-02 16:32:19,105] {{logging_mixin.py:120}} INFO - {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
[2023-12-02 16:32:19,110] {{logging_mixin.py:120}} INFO - ------------ end --------------
[2023-12-02 16:32:19,120] {{logging_mixin.py:120}} INFO - ------------ data --------------
[2023-12-02 16:32:19,123] {{logging_mixin.py:120}} INFO - {'bestMatches': [{'1. symbol': 'IBM', '2. name': 'International Business Machines Corp', '3. type': 'Equity', '4. region': 'United States', '5. marketOpen': '09:30', '6. marketClose': '16:00', '7. timezone': 'UTC-04', '8. currency': 'USD', '9. matchScore': '1.0000'}, {'1. symbol': 'IBML', '2. name': 'iShares iBonds Dec 2023 Term Muni Bond ETF', '3. type': 'ETF', '4. region': 'United States', '5. marketOpen': '09:30', '6. marketClose': '16:00', '7. timezone': 'UTC-04', '8. currency': 'USD', '9. matchScore': '0.8571'}, {'1. symbol': 'IBMM', '2. name': 'iShares iBonds Dec 2024 Term Muni Bond ETF', '3. type': 'ETF', '4. region': 'United States', '5. marketOpen': '09:30', '6. marketClose': '16:00', '7. timezone': 'UTC-04', '8. currency': 'USD', '9. matchScore': '0.8571'}, {'1. symbol': 'IBMN', '2. name': 'iShares iBonds Dec 2025 Term Muni Bond ETF', '3. type': 'ETF', '4. region': 'United States', '5. marketOpen': '09:30', '6. marketClose': '16:00', '7. timezone': 'UTC-04', '8. currency': 'USD', '9. matchScore': '0.8571'}, {'1. symbol': 'IBMO', '2. name': 'iShares iBonds Dec 2026 Term Muni Bond ETF', '3. type': 'ETF', '4. region': 'United States', '5. marketOpen': '09:30', '6. marketClose': '16:00', '7. timezone': 'UTC-04', '8. currency': 'USD', '9. matchScore': '0.8571'}, {'1. symbol': 'IBM.FRK', '2. name': 'International Business Machines', '3. type': 'Equity', '4. region': 'Frankfurt', '5. marketOpen': '08:00', '6. marketClose': '20:00', '7. timezone': 'UTC+02', '8. currency': 'EUR', '9. matchScore': '0.7500'}, {'1. symbol': 'IBM.LON', '2. name': 'International Business Machines Corporation', '3. type': 'Equity', '4. region': 'United Kingdom', '5. marketOpen': '08:00', '6. marketClose': '16:30', '7. timezone': 'UTC+01', '8. currency': 'USD', '9. matchScore': '0.7500'}, {'1. symbol': 'IBM.DEX', '2. name': 'International Business Machines', '3. type': 'Equity', '4. region': 'XETRA', '5. marketOpen': '08:00', '6. marketClose': '20:00', '7. timezone': 'UTC+02', '8. currency': 'EUR', '9. matchScore': '0.6667'}, {'1. symbol': 'IBM0.FRK', '2. name': 'IBM CDR', '3. type': 'Equity', '4. region': 'Frankfurt', '5. marketOpen': '08:00', '6. marketClose': '20:00', '7. timezone': 'UTC+02', '8. currency': 'EUR', '9. matchScore': '0.6667'}, {'1. symbol': 'IBMB34.SAO', '2. name': 'International Business Machines Corp', '3. type': 'Equity', '4. region': 'Brazil/Sao Paolo', '5. marketOpen': '10:00', '6. marketClose': '17:30', '7. timezone': 'UTC-03', '8. currency': 'BRL', '9. matchScore': '0.5000'}]}
[2023-12-02 16:32:19,132] {{logging_mixin.py:120}} INFO - ------------ end --------------
[2023-12-02 16:32:19,134] {{taskinstance.py:1150}} ERROR - Ошибка записи данных: 'timestamp'
Traceback (most recent call last):
  File "/usr/local/airflow/dags/modules/functions.py", line 70, in load_data_psql
    get_date = datetime.utcfromtimestamp(data["timestamp"]).strftime('%Y-%m-%d %H:%M:%S')
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/modules/functions.py", line 83, in load_data_psql
    raise Exception(f'Ошибка записи данных: {error}')
Exception: Ошибка записи данных: 'timestamp'
[2023-12-02 16:32:19,153] {{taskinstance.py:1194}} INFO - Marking task as FAILED. dag_id=hw-3.4, task_id=load_data_psql, execution_date=20231202T155255, start_date=20231202T163217, end_date=20231202T163219
[2023-12-02 16:32:22,649] {{local_task_job.py:102}} INFO - Task exited with return code 1
